url-path = ""
http-port="8081"
author="Rocks"
email="451360994@qq.com"
# 应用系统设置
[setting]
    logpath = "/tmp/log/autocreate"
    assest=""
    cdn=""
    domain=""

cache-mode = 1

debug=true

# 数据库连接
[database]
   [[database.default]]
        host     = "rm-m5ej7taac6s9q49d4eo.mysql.rds.aliyuncs.com"
        port     = "3306"
        user     = "bird"
        pass     = "bird1234"
        name     = "goadmin"
        type     = "mysql"
        role     = "master"
        charset  = "utf8"
        priority = "1"
          debug  = true

[redis]
    disk  = "127.0.0.1:6379,0"
    cache = "127.0.0.1:6379,1"